---
- hosts: all

  handlers:
    - name: Include all handlers
      import_tasks: handlers/main.yml

  tasks:

  - name: Register system to satellite and repos
    include_role:
      name: register-system
    tags:
      - register

  - name: Configure firewall
    include_tasks: tasks/firewall-setup.yml
    vars:
      ports:
        - 443/tcp
        - 80/tcp
        - 111/tcp
    tags:
      - firewall-setup

- hosts: database
  handlers:
    - name: Include all handlers
      import_tasks: handlers/main.yml

  tasks:
  - name: Deploy docker to database container host
    include_tasks: tasks/setup-docker.yml
    vars:
      docker_packages:
        - docker
        - python-docker-py
        - MySQL-python
    when: QUAY_DATABASE_CONTAINERIZE

  - name: Configure firewall
    include_tasks: tasks/firewall-setup.yml
    vars:
      ports:
        - 3306/tcp
      when: QUAY_MYSQL_DEPLOY

  - name: Deploy conatinerized mysql
    include_tasks: tasks/mysql-setup.yml
    when: QUAY_MYSQL_DEPLOY and QUAY_DATABASE_CONTAINERIZE

- hosts: redis
  handlers:
    - name: Include all handlers
      import_tasks: handlers/main.yml

  tasks:
  - name: Deploy docker to redis container host
    include_tasks: tasks/setup-docker.yml
    vars:
      docker_packages:
        - docker
        - python-docker-py
    when: QUAY_REDIS_CONTAINERIZE

  - name: Deploy redis container
    include_tasks: tasks/setup-redis.yml
    when: QUAY_REDIS_CONTAINERIZE

- hosts: quay
  tasks:

  - name: Deploy docker to quay container host
    include_tasks: tasks/setup-docker.yml
    vars:
      docker_packages:
        - docker
        - python-docker-py
