---
- hosts: all

  handlers:
    - name: Include all handlers
      include_tasks: handlers/main.yml

  tasks:

  - name: Register system to satellite and repos
    include_role:
      name: register-system
    tags:
      - register

  - name: Configure firewall
    include_tasks: tasks/firewall-setup.yml
    tags:
      - firewall-setup
