---
- hosts: all
  tasks:

  - name: Register system to satellite and repos
    include_role:
      name: register-system
    tags:
      - register


  - name: Install postgresql 95
    yum:
      - rh-postgresql95
      - rh-postgresql95-postgresql-contrib
    tags:
      - install-postgres