---
- hosts: all

  handlers:
    - name: Include all handlers
      import_tasks: handlers/main.yml

  tasks:

  - name: Register system to satellite and repos
    include_role:
      name: register-system
    tags:
      - register

  - name: Configure firewall
    include_tasks: tasks/firewall-setup.yml
    vars:
      ports:
        - 443/tcp
        - 80/tcp
        - 111/tcp
    tags:
      - firewall-setup
