---
- hosts: all
  tasks:

  - name: Register system to satellite and repos
    include_role:
      name: register-system


  - name: Install postgresql 95
    name:
      - rh-postgresql95
      - rh-postgresql95-postgresql-contrib