---
- hosts: all
  tasks:

  - name: Register system to satellite and repos
    include_role:
      name: register-system
    tags:
      - register


  - name: Install postgresql 95
    yum:
      name:
        - rh-postgresql95
        - rh-postgresql95-postgresql-contrib
      state: latest
    tags:
      - install-postgres

  - name: Install Docker
    yum:
      name: docker 
      state: latest
    tags:
      - install-docker

  - name: Start and enable docker 
    systemd:
      name: docker 
      state: started
      enabled: yes
    tags:
      - start-docker

  - name: Enable firewalld ports for postgresql 
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
      zone: public
    with_items:
      - 8443/tcp
      - 80/tcp
      - 443/tcp
    notify:
      - reload-firewall
    tags:
      - firewalld

  - name: Create env file on target
    template:
      src: mysql-env-file
      dest: ~/mysql-env-file
      state: present

  - name: Total garbage method of deploying mysql container
    command: "docker run \
    --detach \
    --restart=always \
    --env MYSQL_ROOT_PASSWORD={{ MYSQL_ROOT_PASSWORD }} \
    --env MYSQL_USER={{ MYSQL_USER }} \
    --env MYSQL_PASSWORD={{ MYSQL_PASSWORD }} \
    --env MYSQL_DATABASE={{ MYSQL_DATABASE }} \
    --name {{ MYSQL_CONTAINER_NAME }} \
    --privileged=true \
    --publish 3306:3306 \
    -v /var/lib/mysql:/var/lib/mysql/data:Z \
    registry.access.redhat.com/rhscl/mysql-57-rhel7"
    tags:
      - deploy-mysql-container

  handlers:

  - name: reload-firewall
    command: firewall-cmd --reload


  