---
# tasks file for register-system

- name: Register with activationkey and consume subscriptions matching Red Hat Enterprise Server
  redhat_subscription:
    state: present
    activationkey: rhel-7-server-minimal
    org_id: homelab_infra

- name: Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled

- name: Enable all repositories starting with rhel-7-server
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rhel-server-rhscl-7-rpms