---

  - name: Ensure firewalld is installed
    yum:
      name: firewalld
      state: latest

  - name: Ensure firewalld is started
    systemd:
      name: firewalld
      state: started
      enabled: yes
    notify:
      - restart docker

  - name: Enable firewalld ports
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
      zone: public
    with_items: "{{ ports }}"
    notify:
      - reload-firewall
    tags:
      - firewall-setup

