---

  - name: Enable firewalld ports
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
      zone: public
    with_items: "{{ ports }}"
    notify:
      - reload-firewall
    tags:
      - firewall-setup
