---

  - name: Enable firewalld ports
    firewalld:
      port: "{{ ports }}"
      permanent: yes
      state: enabled
      zone: public
    notify:
      - reload-firewall
    tags:
      - firewall-setup
