---

  - name: Make clair working directory
    file:
      path: /mnt/quay/clair/
      owner:
      group:
      mode: '0644'
      state: directory

  - name: Deploy quay config
    template:
      src: templates/clair-config.j2
      dest: /mnt/quay/clair/config.yaml

  - name: Start clair container
    docker_container:
      detach: yes
      restart: yes
      name: "clair"
      published_ports:
        - "6000:6000"
        - "6061:6061"
      image: "quay.io/redhat/clair-jwt:v3.1.3"
      volumes:
        - "/mnt/quay/clair:/clair/config:Z"
    tags:
      - postgres
